name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - master
    paths:
      - 'worker/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: |
          cd worker
          npm install itty-router

      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: 'worker'
          preCommands: |
            echo "Setting secrets..."
            echo "${{ secrets.PAT_TOKEN }}" | wrangler secret put PAT_TOKEN
            echo "${{ github.repository }}" | wrangler secret put GITHUB_REPOSITORY 