name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - master
    paths:
      - 'worker/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: |
          cd worker
          npm install itty-router

      - name: Set Secrets
        run: |
          cd worker
          echo "Setting PAT_TOKEN..."
          npx wrangler secret put PAT_TOKEN <<< "${{ secrets.PAT_TOKEN }}"
          echo "Setting GITHUB_REPOSITORY..."
          npx wrangler secret put GITHUB_REPOSITORY <<< "${{ github.repository }}"
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: 'worker' 