name: Build and Push Docker Image

on:
  push:
    paths:
      - 'Dockerfile'
      - 'requirements.txt'
    branches:
      - master
  workflow_dispatch:  # 允许手动触发

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v2

    - name: 设置 Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: 登录到 DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: 构建并推送
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/video-analyzer:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/video-analyzer:${{ github.sha }}
        cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/video-analyzer:buildcache
        cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/video-analyzer:buildcache,mode=max 