name: Video Analysis

on:
  issues:
    types: [opened, labeled]

jobs:
  analyze:
    runs-on: ubuntu-latest
    # 移除条件判断，先看是否能触发
    # if: contains(github.event.issue.labels.*.name, 'video-analysis') && contains(github.event.issue.labels.*.name, 'pending')
    
    steps:
    - name: 输出调试信息
      run: |
        echo "Event name: ${{ github.event_name }}"
        echo "Issue number: ${{ github.event.issue.number }}"
        echo "Labels: ${{ toJSON(github.event.issue.labels) }}"
        
    - name: 处理视频
      if: contains(github.event.issue.labels.*.name, 'video-analysis') && contains(github.event.issue.labels.*.name, 'pending')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ZHIPUAI_API_KEY: ${{ secrets.ZHIPUAI_API_KEY }}
      run: |
        docker run --rm \
          -e GITHUB_TOKEN \
          -e ZHIPUAI_API_KEY \
          ${{ secrets.DOCKERHUB_USERNAME }}/video-analyzer:latest \
          python -c "
from issue_processor import IssueProcessor
import asyncio

processor = IssueProcessor()
asyncio.run(processor.process_issue(${{ github.event.issue.number }}))
          " 