name: Video Analysis

on:
  issues:
    types: [opened]

jobs:
  analyze:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'video-analysis') && contains(github.event.issue.labels.*.name, 'pending')

    steps:
    - name: 检出代码
      uses: actions/checkout@v2

    - name: 设置 Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: 安装依赖
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg jq
        pip install openai-whisper

    - name: 提取视频 URL
      id: extract_url
      run: |
        echo "::set-output name=video_url::$(echo '${{ github.event.issue.body }}' | grep -oP 'https?://[^\s]+' | head -1)"

    - name: 下载视频
      run: |
        curl -L -H "User-Agent: Mozilla/5.0" "${{ steps.extract_url.outputs.video_url }}" -o video.mp4
        if [ ! -s video.mp4 ]; then echo "Error: Video file is empty or not downloaded properly." && exit 1; fi

    - name: 提取音轨
      run: |
        ffmpeg -v error -i video.mp4 -q:a 0 -map a audio.mp3 || { echo "Error extracting audio"; exit 1; }

    - name: 转写音频
      run: |
        whisper audio.mp3 --output_dir ./transcriptions --task transcribe --output_format srt

    - name: 输出转写结果
      run: |
        if [ -f ./transcriptions/audio.srt ]; then cat ./transcriptions/audio.srt; else echo "Transcription failed"; fi
