name: Video Analysis

on:
  issues:
    types: [opened]

jobs:
  analyze:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'video-analysis') && contains(github.event.issue.labels.*.name, 'pending')
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v2
      
    - name: 构建 Docker 镜像
      run: |
        docker build --no-cache -t ${{ secrets.DOCKERHUB_USERNAME }}/video-analyzer:latest .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/video-analyzer:latest
        
    - name: 输出调试信息
      run: |
        echo "Event name: ${{ github.event_name }}"
        echo "Event type: ${{ github.event.action }}"
        echo "Issue number: ${{ github.event.issue.number }}"
        echo "Labels: ${{ toJSON(github.event.issue.labels) }}"
        
    - name: 检查文件内容
      run: |
        docker run --rm ${{ secrets.DOCKERHUB_USERNAME }}/video-analyzer:latest \
          cat /app/src/issue_processor.py
        
    - name: 处理视频
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ZHIPUAI_API_KEY: ${{ secrets.ZHIPUAI_API_KEY }}
      run: |
        docker run --rm \
          -e GITHUB_TOKEN \
          -e ZHIPUAI_API_KEY \
          ${{ secrets.DOCKERHUB_USERNAME }}/video-analyzer:latest \
          bash -c "cd /app && PYTHONPATH=/app python -c 'from src.issue_processor import IssueProcessor; import asyncio; processor = IssueProcessor(); asyncio.run(processor.process_issue(${{ github.event.issue.number }}))'" 