name: Video Analysis

on:
  issues:
    types: [opened, labeled]

jobs:
  analyze:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'video-analysis') && contains(github.event.issue.labels.*.name, 'pending')
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Process video
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ZHIPUAI_API_KEY: ${{ secrets.ZHIPUAI_API_KEY }}
      run: |
        python -c "
        import asyncio
        from src.issue_processor import IssueProcessor
        
        processor = IssueProcessor()
        asyncio.run(processor.process_issue(${{ github.event.issue.number }}))
        " 