name: Video Analysis

#on:
#  issues:
#    types: [opened]

jobs:
  analyze:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'video-analysis') && contains(github.event.issue.labels.*.name, 'pending')
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v2

    - name: 设置 Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: 安装依赖
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg jq
        pip install openai-whisper

    - name: 处理视频
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ZHIPUAI_API_KEY: ${{ secrets.ZHIPUAI_API_KEY }}
      run: |
        chmod +x .github/workflows/process_video.sh
        .github/workflows/process_video.sh ${{ github.event.issue.number }} 
